In [274]:
print("Welcome to First Edutronic Class")
#this is a comment inside of my Jupypter Notebook

m="This is a hello world"
print(m)

mm=10
m=100

print(mm)
print(m)


Welcome to First Edutronic Class
This is a hello world
10
100


In [279]:
print("Basic Operations")

x=10
print(x)
y=10
print(x+y)
z=x+y
z=1
if x==y : print("are equals")
else : print("are not equals") 
    
modNumber =10%2
print(modNumber)

xxx ='XX'
YYYY = 'YY'
print(xxx+YYYY)

arrT=[1,2,3]
arrZ=[4,5,6]
arrUNION=arrT+arrZ

print(arrUNION)

numberQuarterd = 2 ** 2
print(numberQuarterd)

numberCube = 2 ** 3
print(numberCube)

numberSQRT = 4 ** (1/2)
print(numberSQRT)


Basic Operations
10
20
are equals
0
XXYY
[1, 2, 3, 4, 5, 6]
4
8
2.0


In [287]:
def sumVariables( a, b) :
    return a+b

print(sumVariables(2,3))


def calcCuadra(n) : 
    return n*n

print(calcCuadra(4) )


#High Order Functions

def simplePrint(x, y):
  print("This simple printing by ",x, y)

simplePrint("CESAR","ADVINCULA")


def highOrderFunction(other, functionArgm, *args, **kwargs):
  functionArgm(*args, **kwargs)
  print(other)

highOrderFunction('MyFirstArguemnt', simplePrint, 'Gretting', 'Cesar')


5
16
This simple printing by  CESAR ADVINCULA
This simple printing by  Gretting Cesar
MyFirstArguemnt


In [289]:
print("List Operations")

myList=[10,20,30]
print(myList)


a=[]
a.append(1)
a.append(2)
a.append(3)
a.append(4)
a.append(5)

#print(a[0])
#print(a[1])
#print(a[2])
#print(a[3])

for elemmt in a :
    print(elemmt)

List Operations
[10, 20, 30]
1
2
3
4
5


In [291]:
a =[1,2]
b = [5,5,6,7,8]
c = a+b

print(' c : ',c)
print(' c[0] : ',c[0])
print(' c[5] : ',c[6])

print(' len(a) : ',len(a))
print(' len(b) : ',len(b))
print(' len(c) : ',len(c))

print(' c.count(5) : ',c.count(5))

 c :  [1, 2, 5, 5, 6, 7, 8]
 c[0] :  1
 c[5] :  8
 len(a) :  2
 len(b) :  5
 len(c) :  7
 c.count(5) :  2


In [297]:
print("String Manipulations")

name = "John"
name2 = "Cesar"
print("Hello, %s %s " % (name,name2))
print("Hello, ",name,"!" )

mylist = [1,2,3]
print("A list: %s" % mylist)

String Manipulations
Hello, John Cesar 
Hello,  John !
A list: [1, 2, 3]


In [298]:
#Functions in Python

def sayHelloWorld(person, regards ):
 print("Hello, %s , From My Function!, I wish you %s"%(person,regards  ))

sayHelloWorld("Cesar","HelloGretting")

def sumTwoVariable( a, b):
    print(a+b)

sumTwoVariable(5,6)

def checkName( n):
    if(n=="Israel") : print("Say Hello")
    else : print("Say GoodBye")

def sumElement( primNum, segNum) : 
    return primNum + segNum

def checkEvenOdd( n ) :
    if(n%2==0) : print("Number is even")
    else : print("Number is odd")

print( 4 + sumElement(1,5))
        
checkEvenOdd(2)
checkEvenOdd(7)



Hello, Cesar , From My Function!, I wish you HelloGretting
11
10
Number is even
Number is odd


In [224]:
#High Order Functions

def simplePrint(x, y):
  print("This is comming from the a Simple Function",x, y)

def highOrderFunction(other, functionArgm, *args, **kwargs):
  functionArgm(*args, **kwargs)
  print(other)

highOrderFunction('MyFirstArguemnt', simplePrint, 'Gretting', 'Cesar')

This is comming from the a Simple Function Gretting Cesar
MyFirstArguemnt


In [300]:
#TUPLE
thistuple = ("apple", "banana", "cherry")
print(thistuple[0])
print(thistuple[1])
print(thistuple[2])
print(thistuple[-1])
print(thistuple[-2])
print(thistuple[-3])

thisTupleNumber = (1,2,3)
print(thisTupleNumber[0])
print(thisTupleNumber[1])
print(thisTupleNumber[2])



#print(thistuple[3])

x = ("apple", "banana", "cherry")
y = list(x)
print(x)

y[1] = "kiwi"
x = tuple(y)

print(x)

thistupleA = ("apple", "banana", "cherry")

for elemnt in thistupleA:
  print(elemnt)


apple
banana
cherry
cherry
banana
apple
1
2
3
('apple', 'banana', 'cherry')
('apple', 'kiwi', 'cherry')
apple
banana
cherry


In [304]:
#YOU CANNOT ADD BECAUSE TUPLE IS INMUTABLE
#YOU CAN CHANGE VALUE INSIDE THIS DATA STRUCTURE BUT NOT INSIDE THE TUPLE

thistuple = ("apple", "banana", "cherry")
#thistuple[1] = "orange" # This will raise an error
print(thistuple)

thisList = ["apple", "banana", "cherry"]
thisList[1] = "orange"
print(thisList)


('apple', 'banana', 'cherry')
['apple', 'orange', 'cherry']


In [305]:
#Check Loops 

print("While - Loop")
count = 0
while count < 5:
    print(count)
    count += 1 

print("For - Loop")
newList=[1,2,3,4]   

for element in newList :
    if(element==2) : break
    print(element)

While - Loop
0
1
2
3
4
For - Loop
1


In [306]:
# The dictionaries are Key Value

phonebook = {
    "John" : 938477566,
    "Jack" : 938377264,
    "Jill" : 947662781
}

print(phonebook)
print(phonebook["John"])
print(phonebook["Jack"])
print(phonebook["Jill"])


phonebookByID = {
    "1" : 938477566,
    "2" : 938377264,
    "3" : 947662781
}

print(phonebookByID)
print(phonebookByID["1"])
print(phonebookByID["2"])
print(phonebookByID["3"])


phonebookByID = {
    1 : 938477566,
    2 : 938377264,
    3 : 947662781
}

print(phonebookByID)
print(phonebookByID[1])
print(phonebookByID[2])
print(phonebookByID[3])


{'John': 938477569, 'Jack': 938377264, 'Jill': 947662781}
938477569
938377264
947662781
{'1': 938477566, '2': 938377264, '3': 947662781}
938477566
938377264
947662781
{1: 938477566, 2: 938377264, 3: 947662781}
938477566
938377264
947662781


In [308]:
print("Recursion Fun")

def calFibonnaci( n ) :
    def calFibonnaciIns(iniIter, FinIter, result, resultAnter ) :
        if iniIter <= FinIter : 
                print(result," " , end = '')
                calFibonnaciIns(iniIter +1 , FinIter, result + resultAnter, result )
        else : result
    calFibonnaciIns(1,n,0,1)

calFibonnaci(9)

Recursion Fun
0  1  1  2  3  5  8  13  21  

In [210]:
print("Recursion Fun")

def factorial_recursive(n):
    if n == 1:
        return 1
    else:
        return n * factorial_recursive(n-1)

print("calFactorial ",factorial_recursive(3))

Recursion Fun
calFactorial  6


In [209]:
class MyClass:
    variableInsiClass = "Hello Iam Variable"

    def functionMyClass():
        print("This is a message inside the class.")

myobjectx = MyClass()

myobjectx.variableInsiClass

'Hello Iam Variable'

In [241]:
#Changing numPy
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [309]:
#Import numPy as NP
import numpy as np

a = np.zeros((2,3))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

[[0. 0. 0.]
 [0. 0. 0.]]


In [254]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"



[[1. 1.]]


In [255]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

[[7 7]
 [7 7]]


In [256]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"


[[1. 0.]
 [0. 1.]]


In [257]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]

[[0.52928939 0.78065422]
 [0.31485172 0.465139  ]]


In [311]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a >= 5])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[5 6]


In [238]:
#Numpy

#Some of the key advantages of Numpy arrays are that they are fast, 
#easy to work with, and give users the opportunity to perform calculations across entire arrays.

# Create 2 new lists height and weight
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# Import the numpy package as np
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)

print(np_height)
print(np_weight)
print(type(np_height))


[1.87 1.87 1.82 1.91 1.9  1.85]
[81.65 97.52 95.25 92.98 86.18 88.45]
<class 'numpy.ndarray'>


In [261]:
#Numpy

import numpy as np

x1 = np.array([1,2,3,4])
y2 = np.array([5,6,7,8])


print(x1 + y2)

print(np.add(x1, y2))

[ 6  8 10 12]
[ 6  8 10 12]


In [262]:
#Numpy

import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)

print(np.add(x, y))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))



In [263]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))



[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [264]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [239]:
#Pandas

dict = {"country": ["Brazil", "Russia", "India", "China", "South Africa"],
       "capital": ["Brasilia", "Moscow", "New Dehli", "Beijing", "Pretoria"],
       "area": [8.516, 17.10, 3.286, 9.597, 1.221],
       "population": [200.4, 143.5, 1252, 1357, 52.98] }

import pandas as pd
brics = pd.DataFrame(dict)
print(brics)

        country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Dehli   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98
